# Travis CI build for pygount.
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --requirement dev-requirements.txt
  - python setup.py install

script:
  # Validate coding guidelines.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pre-commit run --all-files; fi
  # Build the distribution archive.
  - python setup.py bdist_wheel
  # Run the test suite.
  - pytest --verbose

after_success:
  - coveralls
